[book]
title = "vfx-rs Documentation"
authors = ["vfx-rs contributors"]
language = "en"
src = "src"

[build]
build-dir = "book"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/vfx-rs/vfx-rs"
edit-url-template = "https://github.com/vfx-rs/vfx-rs/edit/main/docs/{path}"
